name:                thread-utils-finalizers
version:             0.1.0.0
github:              "iand675/thread-utils"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Perform finalization for threads.
category:            Concurrency

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/thread-finalizers#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-prim

library:
  source-dirs: src

tests:
  thread-finalizers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thread-utils-finalizers
